
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Tue Jan 29 10:34:25 CST 2013
//----------------------------------------------------

package pruebaxml;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int VALUESET = 10;
  public static final int NUM = 3;
  public static final int DOSPUNTOS = 5;
  public static final int ITEMS = 9;
  public static final int RECORD = 11;
  public static final int EOF = 0;
  public static final int ID = 2;
  public static final int IGUAL = 4;
  public static final int error = 1;
  public static final int LEVEL = 7;
  public static final int IDITEMS = 8;
  public static final int DICTIONARY = 6;
}

