/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package jdigitador3;

import Conexion.DBClient;
import Conexion.FtpClient;
import Conexion.SFTPClient;
import Conexion.mongoDB;
import com.jcraft.jsch.JSchException;
import java.awt.Component;
import java.awt.image.BufferedImage;
import java.io.File;
import java.io.FileInputStream;
import java.io.FileOutputStream;
import java.io.IOException;
import java.io.OutputStream;
import java.sql.Connection;
import java.sql.SQLException;
import java.util.Properties;
import javax.imageio.ImageIO;
import javax.swing.ButtonGroup;
import javax.swing.JFileChooser;
import javax.swing.JTextField;
import javax.swing.filechooser.FileNameExtensionFilter;


/**
 *
 * @author LUIS
 */
public class Propiedades extends javax.swing.JDialog {

    /**
     * Creates new form Propiedades
     */
   
    static Properties prop = new Properties();
    public Propiedades(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        jButtonSrvArch.setVisible(false);
        
        ButtonGroup group = new ButtonGroup();
        group.add(jRadioButton1);
        group.add(jRadioButton2);
//        jRadioButton2.setSelected(true);
//        jRadioButton1.setSelected(false);
//        jRadioButton1ActionPerformed(null);
        BufferedImage image = null;
        try {
            image = ImageIO.read(
                        this.getClass().getResource("/icons/16/Symbol Configuration.png"));
        } catch (IOException e) {
        }
        this.setIconImage(image);
        
        
       loadProperties();
 
       setProp();
       jPanel7.setVisible(false);
    }

   private static void loadProperties() {

        try {
            prop.load(new FileInputStream("propiedades.properties"));

        } catch (IOException e) {
            e.printStackTrace();
        }
   }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        pathCspro = new javax.swing.JTextField();
        jButtonFCcspro = new javax.swing.JButton();
        txtubicacionarchivos = new javax.swing.JTextField();
        jButtonFileLocal = new javax.swing.JButton();
        jLabel26 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        txtubicacionsa = new javax.swing.JTextField();
        jButtonSrvArch = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        txtusuariosa = new javax.swing.JTextField();
        jLabel27 = new javax.swing.JLabel();
        txtpasssa = new javax.swing.JPasswordField();
        jButtonTestFTP = new javax.swing.JButton();
        jRadioButton1 = new javax.swing.JRadioButton();
        jRadioButton2 = new javax.swing.JRadioButton();
        jLabel3 = new javax.swing.JLabel();
        jPanel6 = new javax.swing.JPanel();
        jLabel25 = new javax.swing.JLabel();
        txtcuestionario = new javax.swing.JTextField();
        jButtonCuetxml = new javax.swing.JButton();
        txtotros = new javax.swing.JTextField();
        jLabel28 = new javax.swing.JLabel();
        jButtonCuetOtros = new javax.swing.JButton();
        txtDicCSPro = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jButtonDicCSPro = new javax.swing.JButton();
        txtcys = new javax.swing.JTextField();
        jLabel30 = new javax.swing.JLabel();
        jButtonCuetCyS = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        txtDicCSProCYS = new javax.swing.JTextField();
        jButtonDicCSProCYS = new javax.swing.JButton();
        jPanel5 = new javax.swing.JPanel();
        jLabel19 = new javax.swing.JLabel();
        txtserbd = new javax.swing.JTextField();
        txtpuertobd = new javax.swing.JTextField();
        jLabel20 = new javax.swing.JLabel();
        txtusuariobd = new javax.swing.JTextField();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        txtnombrebd = new javax.swing.JTextField();
        txtpassbd = new javax.swing.JPasswordField();
        jButtonTest = new javax.swing.JButton();
        barchivoconf = new javax.swing.JButton();
        jPanel7 = new javax.swing.JPanel();
        jLabel29 = new javax.swing.JLabel();
        txtserbdmongo = new javax.swing.JTextField();
        txtusuariobdmongo = new javax.swing.JTextField();
        jLabel31 = new javax.swing.JLabel();
        jLabel32 = new javax.swing.JLabel();
        jLabel33 = new javax.swing.JLabel();
        txtnombrebdmongo = new javax.swing.JTextField();
        txtpassbdmongo = new javax.swing.JPasswordField();
        jButtonTest1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Configuración de propiedades");
        setModal(true);
        setResizable(false);

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/16/Symbol Restricted.png"))); // NOI18N
        jButton1.setText("Cancelar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/16/Symbol Check.png"))); // NOI18N
        jButton2.setText("Guardar");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Archivos Locales"));

        jLabel1.setText("Ubicación de programa CSPRO");

        pathCspro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pathCsproActionPerformed(evt);
            }
        });

        jButtonFCcspro.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/16/Folder.png"))); // NOI18N
        jButtonFCcspro.setText("Abrir");
        jButtonFCcspro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonFCcsproActionPerformed(evt);
            }
        });

        txtubicacionarchivos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtubicacionarchivosActionPerformed(evt);
            }
        });

        jButtonFileLocal.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/16/Folder.png"))); // NOI18N
        jButtonFileLocal.setText("Abrir");
        jButtonFileLocal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonFileLocalActionPerformed(evt);
            }
        });

        jLabel26.setText("Ubicación de archivos digitados locales");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel26)
                            .addComponent(pathCspro, javax.swing.GroupLayout.PREFERRED_SIZE, 307, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtubicacionarchivos, javax.swing.GroupLayout.PREFERRED_SIZE, 307, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButtonFCcspro, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButtonFileLocal, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(pathCspro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonFCcspro))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel26)
                .addGap(9, 9, 9)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtubicacionarchivos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonFileLocal))
                .addContainerGap(14, Short.MAX_VALUE))
        );

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder("Servidor de archivos"));

        txtubicacionsa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtubicacionsaActionPerformed(evt);
            }
        });

        jButtonSrvArch.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/16/Folder Network.png"))); // NOI18N
        jButtonSrvArch.setText("Abrir");

        jLabel2.setText("Ubicación");

        jLabel24.setText("Contraseña");

        txtusuariosa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtusuariosaActionPerformed(evt);
            }
        });

        jLabel27.setText("Usuario");

        txtpasssa.setText("jPasswordField1");

        jButtonTestFTP.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/16/Connection Check.png"))); // NOI18N
        jButtonTestFTP.setText("Test");
        jButtonTestFTP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonTestFTPActionPerformed(evt);
            }
        });

        jRadioButton1.setText("SFTP");
        jRadioButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton1ActionPerformed(evt);
            }
        });

        jRadioButton2.setText("FTP");
        jRadioButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton2ActionPerformed(evt);
            }
        });

        jLabel3.setText("Tipo:");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(35, 35, 35)
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jRadioButton2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jRadioButton1)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(2, 2, 2)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel27)
                                    .addComponent(txtusuariosa, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jLabel24))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(txtpasssa, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addComponent(txtubicacionsa, javax.swing.GroupLayout.PREFERRED_SIZE, 307, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 17, Short.MAX_VALUE)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButtonTestFTP, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButtonSrvArch, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jRadioButton1)
                    .addComponent(jRadioButton2)
                    .addComponent(jLabel3))
                .addGap(6, 6, 6)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtubicacionsa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonSrvArch))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel27)
                    .addComponent(jLabel24))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtusuariosa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtpasssa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonTestFTP))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel6.setBorder(javax.swing.BorderFactory.createTitledBorder("Diccionario"));

        jLabel25.setText("Diccionario Hogar XML");

        txtcuestionario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtcuestionarioActionPerformed(evt);
            }
        });

        jButtonCuetxml.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/16/Folder.png"))); // NOI18N
        jButtonCuetxml.setText("Abrir");
        jButtonCuetxml.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCuetxmlActionPerformed(evt);
            }
        });

        txtotros.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtotrosActionPerformed(evt);
            }
        });

        jLabel28.setText("Diccionario Otros XML");

        jButtonCuetOtros.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/16/Folder.png"))); // NOI18N
        jButtonCuetOtros.setText("Abrir");
        jButtonCuetOtros.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCuetOtrosActionPerformed(evt);
            }
        });

        txtDicCSPro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtDicCSProActionPerformed(evt);
            }
        });

        jLabel4.setText("Diccionario CSPro y Entry. Hogar");

        jButtonDicCSPro.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/16/Folder.png"))); // NOI18N
        jButtonDicCSPro.setText("Abrir");
        jButtonDicCSPro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonDicCSProActionPerformed(evt);
            }
        });

        txtcys.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtcysActionPerformed(evt);
            }
        });

        jLabel30.setText("Diccionario Comunidad y Servicios XML");

        jButtonCuetCyS.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/16/Folder.png"))); // NOI18N
        jButtonCuetCyS.setText("Abrir");
        jButtonCuetCyS.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCuetCySActionPerformed(evt);
            }
        });

        jLabel5.setText("Diccionario CSPro y Entry. Comunidad y Servicios");

        txtDicCSProCYS.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtDicCSProCYSActionPerformed(evt);
            }
        });

        jButtonDicCSProCYS.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/16/Folder.png"))); // NOI18N
        jButtonDicCSProCYS.setText("Abrir");
        jButtonDicCSProCYS.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonDicCSProCYSActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addComponent(jLabel25)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel6Layout.createSequentialGroup()
                                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel30)
                                    .addComponent(jLabel28)
                                    .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addComponent(txtotros, javax.swing.GroupLayout.PREFERRED_SIZE, 307, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(txtcuestionario, javax.swing.GroupLayout.PREFERRED_SIZE, 307, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(txtcys, javax.swing.GroupLayout.PREFERRED_SIZE, 307, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(jPanel6Layout.createSequentialGroup()
                                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel4)
                                    .addComponent(txtDicCSPro, javax.swing.GroupLayout.PREFERRED_SIZE, 307, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButtonCuetxml, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButtonCuetOtros, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButtonCuetCyS, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButtonDicCSPro, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5)
                            .addComponent(txtDicCSProCYS, javax.swing.GroupLayout.PREFERRED_SIZE, 307, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButtonDicCSProCYS, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addComponent(jLabel25)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtcuestionario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonCuetxml))
                .addGap(13, 13, 13)
                .addComponent(jLabel28)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtotros, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonCuetOtros))
                .addGap(13, 13, 13)
                .addComponent(jLabel30)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtcys, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonCuetCyS))
                .addGap(18, 18, 18)
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtDicCSPro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonDicCSPro))
                .addGap(18, 18, 18)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtDicCSProCYS, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonDicCSProCYS))
                .addContainerGap(49, Short.MAX_VALUE))
        );

        jPanel5.setBorder(javax.swing.BorderFactory.createTitledBorder("Base de datos"));
        jPanel5.setName(""); // NOI18N

        jLabel19.setText("Servidor de base de datos");

        txtserbd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtserbdActionPerformed(evt);
            }
        });

        txtpuertobd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtpuertobdActionPerformed(evt);
            }
        });

        jLabel20.setText("Puerto");

        txtusuariobd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtusuariobdActionPerformed(evt);
            }
        });

        jLabel21.setText("Usuario");

        jLabel22.setText("Contraseña");

        jLabel23.setText("Nombre");

        txtnombrebd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtnombrebdActionPerformed(evt);
            }
        });

        txtpassbd.setText("jPasswordField1");

        jButtonTest.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/16/Connection Check.png"))); // NOI18N
        jButtonTest.setText("Test");
        jButtonTest.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonTestActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(txtusuariobd, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtpassbd, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButtonTest, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel5Layout.createSequentialGroup()
                                .addComponent(jLabel21)
                                .addGap(129, 129, 129)
                                .addComponent(jLabel22))
                            .addGroup(jPanel5Layout.createSequentialGroup()
                                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtserbd, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel19, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtpuertobd, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel20, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel23)
                                    .addComponent(txtnombrebd, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(jLabel19)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtserbd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(jLabel20)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtpuertobd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(jLabel23)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtnombrebd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel21)
                    .addComponent(jLabel22))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtusuariobd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtpassbd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonTest))
                .addContainerGap())
        );

        barchivoconf.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/16/Folder.png"))); // NOI18N
        barchivoconf.setText("Abrir archivo de Configuración");
        barchivoconf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                barchivoconfActionPerformed(evt);
            }
        });

        jPanel7.setBorder(javax.swing.BorderFactory.createTitledBorder("Base de datos de digitación"));

        jLabel29.setText("Servidor de base de datos");

        txtserbdmongo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtserbdmongoActionPerformed(evt);
            }
        });

        txtusuariobdmongo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtusuariobdmongoActionPerformed(evt);
            }
        });

        jLabel31.setText("Usuario");

        jLabel32.setText("Contraseña");

        jLabel33.setText("Nombre");

        txtnombrebdmongo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtnombrebdmongoActionPerformed(evt);
            }
        });

        txtpassbdmongo.setText("jPasswordField1");

        jButtonTest1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/16/Connection Check.png"))); // NOI18N
        jButtonTest1.setText("Test");
        jButtonTest1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonTest1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addComponent(txtusuariobdmongo, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtpassbdmongo))
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel29)
                            .addComponent(txtserbdmongo, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel31))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel32)
                            .addComponent(jLabel33)
                            .addComponent(txtnombrebdmongo, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButtonTest1, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel29)
                    .addComponent(jLabel33))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtserbdmongo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtnombrebdmongo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel31)
                    .addComponent(jLabel32))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtusuariobdmongo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtpassbdmongo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonTest1))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(barchivoconf)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton1)
                        .addContainerGap())
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jPanel2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addContainerGap())))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jButton1)
                        .addComponent(jButton2))
                    .addComponent(barchivoconf))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtubicacionsaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtubicacionsaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtubicacionsaActionPerformed

    private void txtcuestionarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtcuestionarioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtcuestionarioActionPerformed

    private void txtubicacionarchivosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtubicacionarchivosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtubicacionarchivosActionPerformed

    private void pathCsproActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pathCsproActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_pathCsproActionPerformed

    private void txtusuariosaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtusuariosaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtusuariosaActionPerformed

    private void txtotrosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtotrosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtotrosActionPerformed

    private void jButtonFCcsproActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonFCcsproActionPerformed
        seleccionarDir(pathCspro);
    }//GEN-LAST:event_jButtonFCcsproActionPerformed

    private void jButtonFileLocalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonFileLocalActionPerformed
        seleccionarDir(txtubicacionarchivos);
    }//GEN-LAST:event_jButtonFileLocalActionPerformed

    private void jButtonCuetxmlActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCuetxmlActionPerformed
        seleccionarArc(txtcuestionario);
    }//GEN-LAST:event_jButtonCuetxmlActionPerformed

    private void jButtonCuetOtrosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCuetOtrosActionPerformed
        seleccionarArc(txtotros);
    }//GEN-LAST:event_jButtonCuetOtrosActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed

        prop.setProperty("cspro", pathCspro.getText());
        prop.setProperty("archdigitado", txtubicacionarchivos.getText());  
        prop.setProperty("servidorarch", txtubicacionsa.getText());
        prop.setProperty("usuarioarch", txtusuariosa.getText());
        prop.setProperty("passarch", String.valueOf(txtpasssa.getPassword()));
        prop.setProperty("usuariobd", txtusuariobd.getText());
        prop.setProperty("passbd", String.valueOf(txtpassbd.getPassword()));
        prop.setProperty("nombrebd", txtnombrebd.getText());
        prop.setProperty("puertobd", txtpuertobd.getText());
        prop.setProperty("servidorbd", txtserbd.getText());
        prop.setProperty("dirXML", txtcuestionario.getText());
        prop.setProperty("dirOtros", txtotros.getText());
        prop.setProperty("dirCyS", txtcys.getText());
        
        prop.setProperty("usuarioMongoDB",txtusuariobdmongo.getText());
        prop.setProperty("passMongoDB",String.valueOf(txtpassbdmongo.getPassword()));
        prop.setProperty("servidorMongoDB",txtserbdmongo.getText());
        prop.setProperty("nombreMongoDB",txtnombrebdmongo.getText());
        
        prop.setProperty("dicCSPro", txtDicCSPro.getText());
        prop.setProperty("dicCSProCYS", txtDicCSProCYS.getText());        
        
        String esFTP = "";
        if(jRadioButton1.isSelected()){
            esFTP = "no";
        }else if(jRadioButton2.isSelected()){
            esFTP = "si";
        }
        prop.setProperty("FTP",esFTP);
        
        guardarPropiedades();

        this.dispose();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        this.dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void barchivoconfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_barchivoconfActionPerformed
        Component cmd = null; ///<---- aqui guarda el contenido del archivo
        JFileChooser jf = new JFileChooser();
        String dirName = "";
        FileNameExtensionFilter filter = new FileNameExtensionFilter("PROPERTIES", "properties");
        jf.setFileFilter(filter);
        try {
            int code = jf.showOpenDialog(cmd);
            if (code == JFileChooser.APPROVE_OPTION) {
                File selectedFile = jf.getSelectedFile();
                dirName = selectedFile.getName();
                selectedFile.getAbsolutePath();
                
                try {
                        prop.load(new FileInputStream(jf.getCurrentDirectory().toString()+"\\"+dirName));
                        setProp();
                    } catch (IOException e) {
                        e.printStackTrace();
                    }
            }

        } catch (Exception f) {
        }
    }//GEN-LAST:event_barchivoconfActionPerformed

    private void jButtonTestFTPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonTestFTPActionPerformed
        if(Login.esFTP){
            FtpClient ftp = new FtpClient();
            boolean ftpcon = ftp.conexion(txtubicacionsa.getText(), txtusuariosa.getText(), String.valueOf(txtpasssa.getPassword()),22);
            Mensajes msj = new Mensajes();
            if(ftpcon) {              
                msj.info("¡Conexion correcta con el servidor ftp!", "Información");
                ftp.disconnect();
            }else{
                msj.error("¡No se puede conectar con el servidor ftp!", "Error");
            }
        }else{
            try {
                SFTPClient ftp = new SFTPClient();
                boolean ftpcon = ftp.conexion(txtubicacionsa.getText(), txtusuariosa.getText(), String.valueOf(txtpasssa.getPassword()),22);
                Mensajes msj = new Mensajes();
                if(ftpcon) {              
                    msj.info("¡Conexion correcta con el servidor sftp!", "Información");
                    ftp.disconnect();
                }else{
                    msj.error("¡No se puede conectar con el servidor sftp!", "Error");
                }
            } catch (JSchException ex) {
    //            Logger.getLogger(Propiedades.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }//GEN-LAST:event_jButtonTestFTPActionPerformed

    private void txtserbdmongoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtserbdmongoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtserbdmongoActionPerformed

    private void txtusuariobdmongoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtusuariobdmongoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtusuariobdmongoActionPerformed

    private void txtnombrebdmongoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtnombrebdmongoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtnombrebdmongoActionPerformed

    private void jButtonTest1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonTest1ActionPerformed
        /* 
        Mensajes msj = new Mensajes();
        mongoDB a = new mongoDB();
        try{
        boolean prueba = a.mongoDB(txtserbdmongo.getText(), txtnombrebdmongo.getText(),
            txtusuariobdmongo.getText(), String.valueOf(txtpassbdmongo.getPassword()));
            if(prueba) {              
                msj.info("¡Conexion correcta con el servidor de MongoDB!", "Información");
                a.Disconnect();
            }else{
                msj.error("¡No se puede conectar con el servidor de MongoDB!", "Error");
            }
        }catch(Exception e){
            msj.error("¡No se puede conectar con el servidor de MongoDB!", "Error");
        }
        */
    }//GEN-LAST:event_jButtonTest1ActionPerformed

    private void jRadioButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton1ActionPerformed
        if(jRadioButton1.isSelected()){
            Login.esFTP = false;
        }else if(jRadioButton2.isSelected()){
            Login.esFTP = true;
        }
    }//GEN-LAST:event_jRadioButton1ActionPerformed

    private void jRadioButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton2ActionPerformed
        if(jRadioButton1.isSelected()){
            Login.esFTP = false;
        }else if(jRadioButton2.isSelected()){
            Login.esFTP = true;
        }
    }//GEN-LAST:event_jRadioButton2ActionPerformed

    private void txtDicCSProActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtDicCSProActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtDicCSProActionPerformed

    private void jButtonDicCSProActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonDicCSProActionPerformed
        seleccionarDir(txtDicCSPro);
    }//GEN-LAST:event_jButtonDicCSProActionPerformed

    private void txtcysActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtcysActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtcysActionPerformed

    private void jButtonCuetCySActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCuetCySActionPerformed
        seleccionarArc(txtcys);
    }//GEN-LAST:event_jButtonCuetCySActionPerformed

    private void jButtonTestActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonTestActionPerformed
        try {
            Connection c = new DBClient().getConnection(getDireccionBD(),getNombreBD(),getUsuarioBD(),getPassBD()
                ,getPuertoBD());
            Mensajes msj = new Mensajes();
            msj.info("¡Conexion correcta con la base de datos!", "Información");
            c.close();
        } catch (SQLException ex) {
            Mensajes msj = new Mensajes();
            msj.error("¡Error en la conexion con la base de datos!", "Error");
        }
    }//GEN-LAST:event_jButtonTestActionPerformed

    private void txtnombrebdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtnombrebdActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtnombrebdActionPerformed

    private void txtusuariobdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtusuariobdActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtusuariobdActionPerformed

    private void txtpuertobdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtpuertobdActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtpuertobdActionPerformed

    private void txtserbdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtserbdActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtserbdActionPerformed

    private void txtDicCSProCYSActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtDicCSProCYSActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtDicCSProCYSActionPerformed

    private void jButtonDicCSProCYSActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonDicCSProCYSActionPerformed
        seleccionarDir(txtDicCSProCYS);
    }//GEN-LAST:event_jButtonDicCSProCYSActionPerformed

    public void seleccionarDir(JTextField jt){
    
    Component cmd = null; ///<---- aqui guarda el contenido del archivo
        JFileChooser jf = new JFileChooser();
        String dirName = "";
        jf.setFileSelectionMode(JFileChooser.DIRECTORIES_ONLY);

        try {
            int code = jf.showOpenDialog(cmd);
            if (code == JFileChooser.APPROVE_OPTION) {
                File selectedFile = jf.getSelectedFile();
                dirName = selectedFile.getName();
                jt.setText(jf.getCurrentDirectory().toString()+"\\"+dirName);
                
            }

        } catch (Exception f) {
        }
        
    }
    
    public void seleccionarArc(JTextField jt){
    
    Component cmd = null; ///<---- aqui guarda el contenido del archivo
        JFileChooser jf = new JFileChooser();
        String dirName = "";
        jf.setFileSelectionMode(JFileChooser.FILES_ONLY);

        try {
            int code = jf.showOpenDialog(cmd);
            if (code == JFileChooser.APPROVE_OPTION) {
                File selectedFile = jf.getSelectedFile();
                dirName = selectedFile.getName();
                jt.setText(jf.getCurrentDirectory().toString()+"\\"+dirName);
                
            }

        } catch (Exception f) {
        }
        
    }
        
    public String getpathCSpro(){return pathCspro.getText();}
    
    public String getUbicacionArchivos(){return txtubicacionarchivos.getText();}
    
    public String getDireccionSA(){return txtubicacionsa.getText();}
    
    public String getUsuarioSA(){return txtusuariosa.getText();}
    
    public String getPassSA(){return String.valueOf(txtpasssa.getPassword());}
    
    public String getDireccionBD(){return txtserbd.getText();}
    
    public String getUsuarioBD(){return txtusuariobd.getText();}
    
    public String getPassBD(){return String.valueOf(txtpassbd.getPassword());}
    
    public String getPuertoBD(){return txtpuertobd.getText();}
    
    public String getNombreBD(){return txtnombrebd.getText();}
    
    public String getDirXML(){return txtcuestionario.getText();}
    
    public String getDirOtros(){return txtotros.getText();}
    
    public String getDirCyS(){return txtcys.getText();}
    
    public String getDireccionBDMongo(){return txtserbdmongo.getText();}
    
    public String getUsuarioBDMongo(){return txtusuariobdmongo.getText();}
    
    public String getPassBDMongo(){return String.valueOf(txtpassbdmongo.getPassword());}
    
    public String getNombreBDMongo(){return txtnombrebdmongo.getText();}
    
    public String getDicCSPro(){return txtDicCSPro.getText();}
    
    public String getDicCSProCYS(){return txtDicCSProCYS.getText();}
    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton barchivoconf;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButtonCuetCyS;
    private javax.swing.JButton jButtonCuetOtros;
    private javax.swing.JButton jButtonCuetxml;
    private javax.swing.JButton jButtonDicCSPro;
    private javax.swing.JButton jButtonDicCSProCYS;
    private javax.swing.JButton jButtonFCcspro;
    private javax.swing.JButton jButtonFileLocal;
    private javax.swing.JButton jButtonSrvArch;
    private javax.swing.JButton jButtonTest;
    private javax.swing.JButton jButtonTest1;
    private javax.swing.JButton jButtonTestFTP;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JRadioButton jRadioButton1;
    private javax.swing.JRadioButton jRadioButton2;
    private javax.swing.JTextField pathCspro;
    private javax.swing.JTextField txtDicCSPro;
    private javax.swing.JTextField txtDicCSProCYS;
    private javax.swing.JTextField txtcuestionario;
    private javax.swing.JTextField txtcys;
    private javax.swing.JTextField txtnombrebd;
    private javax.swing.JTextField txtnombrebdmongo;
    private javax.swing.JTextField txtotros;
    private javax.swing.JPasswordField txtpassbd;
    private javax.swing.JPasswordField txtpassbdmongo;
    private javax.swing.JPasswordField txtpasssa;
    private javax.swing.JTextField txtpuertobd;
    private javax.swing.JTextField txtserbd;
    private javax.swing.JTextField txtserbdmongo;
    private javax.swing.JTextField txtubicacionarchivos;
    private javax.swing.JTextField txtubicacionsa;
    private javax.swing.JTextField txtusuariobd;
    private javax.swing.JTextField txtusuariobdmongo;
    private javax.swing.JTextField txtusuariosa;
    // End of variables declaration//GEN-END:variables

    private void guardarPropiedades() {
 
               try{ 
                OutputStream out = new FileOutputStream("propiedades.properties");
                prop.store(out, "Propiedades jdigitador");
                out.flush();
                out.close();
               }catch(Exception e){System.err.println("ERROR PROPIEDADES!");}
  
       
    }

    private void setProp() {
        pathCspro.setText(prop.getProperty("cspro"));
        txtubicacionarchivos.setText(prop.getProperty("archdigitado"));
        
        txtubicacionsa.setText(prop.getProperty("servidorarch"));
        txtusuariosa.setText(prop.getProperty("usuarioarch"));
        txtpasssa.setText(prop.getProperty("passarch"));
        
        txtusuariobd.setText(prop.getProperty("usuariobd"));
        txtpassbd.setText(prop.getProperty("passbd"));
        txtnombrebd.setText(prop.getProperty("nombrebd"));
        txtpuertobd.setText(prop.getProperty("puertobd"));
        txtserbd.setText(prop.getProperty("servidorbd"));
        
        txtcuestionario.setText(prop.getProperty("dirXML"));
        txtotros.setText(prop.getProperty("dirOtros"));
        txtcys.setText(prop.getProperty("dirCyS"));
        
        txtusuariobdmongo.setText(prop.getProperty("usuarioMongoDB"));
        txtpassbdmongo.setText(prop.getProperty("passMongoDB"));
        txtserbdmongo.setText(prop.getProperty("servidorMongoDB"));
        txtnombrebdmongo.setText(prop.getProperty("nombreMongoDB"));
        
        
        txtDicCSPro.setText(prop.getProperty("dicCSPro"));
        
        txtDicCSProCYS.setText(prop.getProperty("dicCSProCYS"));
        
        String esFTP = prop.getProperty("FTP");
        
        
        if(esFTP.equals("no")){
                jRadioButton1.setSelected(true);
                Login.esFTP = false;
        }else if(esFTP.equals("si")){
                jRadioButton2.setSelected(true);
                Login.esFTP = true;
        }
        
    }
}
